export const HERO_WORDS = [
  {
    id: 'financiamiento',
    label: 'Financiamiento',
    accent: true,
    x: -39,
    y: -24,
    scale: 1.08,
    opacity: 0.88,
    blur: 0,
    rotation: -1.4,
    curveX: -7,
    curveY: 7,
    targetX: -4.5,
    targetY: -8,
    start: 0.10,
    end: 0.54,
    mobile: { x: -29, y: -24, scale: 0.92 },
  },
  {
    id: 'liquidez',
    label: 'Liquidez',
    accent: false,
    x: -45,
    y: 1,
    scale: 0.82,
    opacity: 0.62,
    blur: 1,
    rotation: 1.2,
    curveX: -4,
    curveY: -7,
    targetX: -7,
    targetY: 1,
    start: 0.12,
    end: 0.57,
    mobile: { x: -31, y: 3, scale: 0.74 },
  },
  {
    id: 'medios-pago',
    label: 'Medios de pago',
    accent: true,
    x: 38,
    y: 13,
    scale: 1.00,
    opacity: 0.82,
    blur: 0.2,
    rotation: -1,
    curveX: 6,
    curveY: -5,
    targetX: 5,
    targetY: 5,
    start: 0.13,
    end: 0.59,
    mobile: { x: 25, y: 14, scale: 0.84 },
  },
  {
    id: 'procesos-ia',
    label: 'Procesos con IA',
    accent: false,
    x: -25,
    y: 29,
    scale: 0.90,
    opacity: 0.67,
    blur: 0.7,
    rotation: 1.4,
    curveX: 7,
    curveY: 6,
    targetX: -2,
    targetY: 7,
    start: 0.14,
    end: 0.60,
    mobile: { x: -24, y: 27, scale: 0.78 },
  },
  {
    id: 'inversiones',
    label: 'Inversiones',
    accent: false,
    x: 31,
    y: -29,
    scale: 0.86,
    opacity: 0.58,
    blur: 1.2,
    rotation: 1.6,
    curveX: -5,
    curveY: 8,
    targetX: 4,
    targetY: -7,
    start: 0.15,
    end: 0.61,
    mobile: { x: 24, y: -24, scale: 0.74 },
  },
  {
    id: 'estrategia',
    label: 'Estrategia',
    accent: true,
    x: 44,
    y: -5,
    scale: 0.76,
    opacity: 0.56,
    blur: 1.5,
    rotation: -1.5,
    curveX: 5,
    curveY: 8,
    targetX: 7,
    targetY: -1,
    start: 0.16,
    end: 0.62,
    mobile: { x: 30, y: -2, scale: 0.70 },
  },
  {
    id: 'mercado-capitales',
    label: 'Mercado de capitales',
    accent: false,
    x: 23,
    y: 34,
    scale: 0.71,
    opacity: 0.47,
    blur: 2,
    rotation: 1.3,
    curveX: -7,
    curveY: 4,
    targetX: 4,
    targetY: 8,
    start: 0.18,
    end: 0.63,
  },
  {
    id: 'ejecucion',
    label: 'Ejecución',
    accent: false,
    x: -8,
    y: -35,
    scale: 0.68,
    opacity: 0.45,
    blur: 2.2,
    rotation: -1.8,
    curveX: 8,
    curveY: -4,
    targetX: -1,
    targetY: -9,
    start: 0.19,
    end: 0.64,
  },
  {
    id: 'resultados',
    label: 'Resultados',
    accent: true,
    x: 10,
    y: 5,
    scale: 1.16,
    opacity: 0.88,
    blur: 0,
    rotation: 0.8,
    curveX: 10,
    curveY: -8,
    targetX: 2,
    targetY: 1,
    start: 0.20,
    end: 0.65,
  },
  {
    id: 'respaldo',
    label: 'Respaldo',
    accent: false,
    x: -36,
    y: 20,
    scale: 0.74,
    opacity: 0.50,
    blur: 1.7,
    rotation: 1.5,
    curveX: -6,
    curveY: -4,
    targetX: -6,
    targetY: 5,
    start: 0.21,
    end: 0.66,
  },
  {
    id: 'crecimiento',
    label: 'Crecimiento',
    accent: false,
    x: 39,
    y: 28,
    scale: 0.78,
    opacity: 0.51,
    blur: 1.5,
    rotation: -1.2,
    curveX: 6,
    curveY: 5,
    targetX: 6,
    targetY: 7,
    start: 0.22,
    end: 0.67,
  },
  {
    id: 'gestion-integral',
    label: 'Gestión integral',
    accent: false,
    x: 4,
    y: -21,
    scale: 0.78,
    opacity: 0.54,
    blur: 1.3,
    rotation: 1.1,
    curveX: -8,
    curveY: -6,
    targetX: 1,
    targetY: -6,
    start: 0.23,
    end: 0.68,
  },
];

export const HERO_WORD_LAYOUTS = {
  desktop: {
    scrollVh: 245,
    xFactor: 1,
    yFactor: 1,
    visibleIds: HERO_WORDS.map((word) => word.id),
  },
  tablet: {
    scrollVh: 225,
    xFactor: 0.78,
    yFactor: 0.86,
    visibleIds: HERO_WORDS.slice(0, 10).map((word) => word.id),
  },
  mobile: {
    scrollVh: 205,
    xFactor: 1,
    yFactor: 0.88,
    visibleIds: HERO_WORDS.slice(0, 6).map((word) => word.id),
  },
};

export const HERO_MARK_REVEALS = [
  {
    id: 'cream-top',
    axis: 'x',
    origin: 'left center',
    at: 0.16,
    duration: 0.20,
    scanAxis: 'x',
    scanFrom: -12,
    scanTo: 58,
  },
  {
    id: 'cream-bottom',
    axis: 'x',
    origin: 'right center',
    at: 0.28,
    duration: 0.21,
    scanAxis: 'x',
    scanFrom: 66,
    scanTo: -8,
  },
  {
    id: 'gold-top',
    axis: 'y',
    origin: 'center top',
    at: 0.40,
    duration: 0.19,
    scanAxis: 'y',
    scanFrom: -10,
    scanTo: 34,
  },
  {
    id: 'gold-bottom',
    axis: 'y',
    origin: 'center bottom',
    at: 0.50,
    duration: 0.18,
    scanAxis: 'y',
    scanFrom: 70,
    scanTo: 24,
  },
];
