export const HERO_WORDS = [
  {
    id: 'financiamiento',
    label: 'Financiamiento',
    size: 'xl',
    accent: true,
    front: true,
    x: -39,
    y: -22,
    opacity: 0.94,
    blur: 0,
    rotation: -1.2,
    curveX: -5,
    curveY: 7,
    targetX: -2.8,
    targetY: -1.8,
    start: 0.025,
    end: 0.50,
    floatX: 12,
    floatY: -9,
    floatRotate: 1.2,
    floatDuration: 6.8,
    floatDelay: -2.4,
    tablet: { x: -35, y: -21 },
    mobile: { x: -27, y: -22 },
  },
  {
    id: 'liquidez',
    label: 'Liquidez',
    size: 'md',
    x: -46,
    y: 2,
    opacity: 0.62,
    blur: 1,
    rotation: 1.1,
    curveX: -3,
    curveY: -7,
    targetX: -3.5,
    targetY: 0.5,
    start: 0.045,
    end: 0.53,
    floatX: -10,
    floatY: 8,
    floatRotate: -1.4,
    floatDuration: 7.4,
    floatDelay: -5.1,
    tablet: { x: -39, y: 3 },
    mobile: { x: -29, y: 2 },
  },
  {
    id: 'medios-pago',
    label: 'Medios de pago',
    size: 'lg',
    accent: true,
    front: true,
    x: 38,
    y: 14,
    opacity: 0.88,
    blur: 0,
    rotation: -0.8,
    curveX: 6,
    curveY: -5,
    targetX: 3.1,
    targetY: 1.7,
    start: 0.055,
    end: 0.55,
    floatX: 11,
    floatY: 7,
    floatRotate: 1,
    floatDuration: 6.2,
    floatDelay: -1.7,
    tablet: { x: 34, y: 15 },
    mobile: { x: 27, y: 14 },
  },
  {
    id: 'procesos-ia',
    label: 'Procesos con IA',
    size: 'lg',
    x: -27,
    y: 31,
    opacity: 0.72,
    blur: 0.6,
    rotation: 1.3,
    curveX: 7,
    curveY: 5,
    targetX: -1.4,
    targetY: 2.4,
    start: 0.065,
    end: 0.57,
    floatX: -8,
    floatY: -11,
    floatRotate: -1.1,
    floatDuration: 7.1,
    floatDelay: -3.2,
    tablet: { x: -25, y: 29 },
    mobile: { x: -24, y: 26 },
  },
  {
    id: 'inversiones',
    label: 'Inversiones',
    size: 'md',
    x: 31,
    y: -28,
    opacity: 0.58,
    blur: 1.2,
    rotation: 1.5,
    curveX: -5,
    curveY: 8,
    targetX: 2.4,
    targetY: -2.3,
    start: 0.075,
    end: 0.58,
    floatX: 9,
    floatY: -7,
    floatRotate: -1.5,
    floatDuration: 8.1,
    floatDelay: -4.4,
    tablet: { x: 28, y: -27 },
    mobile: { x: 24, y: -23 },
  },
  {
    id: 'mercado-capitales',
    label: 'Mercado de capitales',
    size: 'sm',
    depth: 'far',
    x: 23,
    y: 35,
    opacity: 0.42,
    blur: 2.1,
    rotation: 1,
    curveX: -7,
    curveY: 3,
    targetX: 2.2,
    targetY: 3,
    start: 0.095,
    end: 0.61,
    floatX: -7,
    floatY: 8,
    floatRotate: 1.4,
    floatDuration: 8.7,
    floatDelay: -6.3,
    tablet: { x: 22, y: 32 },
    mobileHidden: true,
  },
  {
    id: 'capital-trabajo',
    label: 'Capital de trabajo',
    size: 'sm',
    depth: 'far',
    x: -5,
    y: -35,
    opacity: 0.40,
    blur: 2.4,
    rotation: -1.7,
    curveX: 8,
    curveY: -4,
    targetX: -0.4,
    targetY: -3,
    start: 0.105,
    end: 0.62,
    floatX: 7,
    floatY: 10,
    floatRotate: 1.2,
    floatDuration: 7.8,
    floatDelay: -2.9,
    tablet: { x: -4, y: -32 },
    mobileHidden: true,
  },
  {
    id: 'cobros-pagos',
    label: 'Cobros y pagos',
    size: 'md',
    x: 45,
    y: -4,
    opacity: 0.54,
    blur: 1.4,
    rotation: -1.4,
    curveX: 5,
    curveY: 7,
    targetX: 3.6,
    targetY: -0.3,
    start: 0.115,
    end: 0.63,
    floatX: -12,
    floatY: -6,
    floatRotate: -1.1,
    floatDuration: 6.9,
    floatDelay: -5.8,
    tablet: { x: 40, y: -3 },
    mobileHidden: true,
  },
  {
    id: 'estrategia',
    label: 'Estrategia',
    size: 'xl',
    accent: true,
    front: true,
    x: 8,
    y: 7,
    opacity: 0.90,
    blur: 0,
    rotation: 0.7,
    curveX: 9,
    curveY: -7,
    targetX: 0.9,
    targetY: 0.4,
    start: 0.125,
    end: 0.64,
    floatX: 10,
    floatY: -8,
    floatRotate: -0.9,
    floatDuration: 6.4,
    floatDelay: -3.6,
    mobile: { x: 20, y: 3 },
  },
  {
    id: 'automatizacion',
    label: 'Automatización',
    size: 'sm',
    x: -37,
    y: 19,
    opacity: 0.49,
    blur: 1.7,
    rotation: 1.4,
    curveX: -6,
    curveY: -4,
    targetX: -3,
    targetY: 1.4,
    start: 0.135,
    end: 0.65,
    floatX: 8,
    floatY: 7,
    floatRotate: 1.3,
    floatDuration: 7.7,
    floatDelay: -4.8,
    tablet: { x: -34, y: 20 },
    mobile: { x: -26, y: 17 },
  },
  {
    id: 'gestion-integral',
    label: 'Gestión integral',
    size: 'md',
    x: 39,
    y: 29,
    opacity: 0.53,
    blur: 1.3,
    rotation: -1,
    curveX: 6,
    curveY: 4,
    targetX: 3.1,
    targetY: 2.7,
    start: 0.145,
    end: 0.66,
    floatX: -9,
    floatY: 9,
    floatRotate: -1.4,
    floatDuration: 8.4,
    floatDelay: -1.1,
    tablet: { x: 35, y: 28 },
    mobileHidden: true,
  },
  {
    id: 'respaldo',
    label: 'Respaldo',
    size: 'sm',
    x: 3,
    y: -21,
    opacity: 0.48,
    blur: 1.8,
    rotation: 1,
    curveX: -8,
    curveY: -6,
    targetX: 0.2,
    targetY: -1.8,
    start: 0.155,
    end: 0.67,
    floatX: 7,
    floatY: -9,
    floatRotate: 1.1,
    floatDuration: 7.3,
    floatDelay: -6,
    mobileHidden: true,
  },
  {
    id: 'crecimiento',
    label: 'Crecimiento',
    size: 'md',
    x: -18,
    y: -10,
    opacity: 0.56,
    blur: 1,
    rotation: -0.9,
    curveX: 5,
    curveY: 5,
    targetX: -1.5,
    targetY: -0.8,
    start: 0.165,
    end: 0.68,
    floatX: -8,
    floatY: 6,
    floatRotate: -1.2,
    floatDuration: 6.6,
    floatDelay: -2.1,
    mobileHidden: true,
  },
  {
    id: 'ejecucion',
    label: 'Ejecución',
    size: 'xs',
    depth: 'far',
    x: 49,
    y: -30,
    opacity: 0.34,
    blur: 2.8,
    rotation: -1.8,
    curveX: -4,
    curveY: 7,
    targetX: 3.8,
    targetY: -2.6,
    start: 0.175,
    end: 0.69,
    floatX: 8,
    floatY: -7,
    floatRotate: 1.5,
    floatDuration: 9.1,
    floatDelay: -5.5,
    tabletHidden: true,
    mobileHidden: true,
  },
  {
    id: 'resultados',
    label: 'Resultados',
    size: 'sm',
    accent: true,
    x: -49,
    y: -34,
    opacity: 0.46,
    blur: 2,
    rotation: 1.6,
    curveX: 6,
    curveY: 6,
    targetX: -3.9,
    targetY: -2.8,
    start: 0.185,
    end: 0.70,
    floatX: -9,
    floatY: -8,
    floatRotate: -1.3,
    floatDuration: 8.8,
    floatDelay: -3.9,
    tabletHidden: true,
    mobile: { x: 27, y: -4 },
  },
  {
    id: 'soluciones-financieras',
    label: 'Soluciones financieras',
    size: 'xs',
    depth: 'far',
    x: 4,
    y: 39,
    opacity: 0.32,
    blur: 3,
    rotation: -1.1,
    curveX: -7,
    curveY: -3,
    targetX: 0.4,
    targetY: 3.4,
    start: 0.195,
    end: 0.71,
    floatX: 6,
    floatY: 8,
    floatRotate: 1.5,
    floatDuration: 9.4,
    floatDelay: -7.2,
    tabletHidden: true,
    mobileHidden: true,
  },
];

export const HERO_WORD_LAYOUTS = {
  desktop: {
    scrollVh: 285,
    xFactor: 1,
    yFactor: 1,
  },
  tablet: {
    scrollVh: 255,
    xFactor: 1,
    yFactor: 1,
  },
  mobile: {
    scrollVh: 215,
    xFactor: 1,
    yFactor: 1,
  },
};

export const HERO_MARK_REVEALS = [
  {
    id: 'cream-a',
    axis: 'x',
    origin: 'left center',
    at: 0.12,
    duration: 0.22,
    scanAxis: 'x',
    scanFrom: -12,
    scanTo: 58,
  },
  {
    id: 'cream-b',
    axis: 'x',
    origin: 'right center',
    at: 0.27,
    duration: 0.24,
    scanAxis: 'x',
    scanFrom: 68,
    scanTo: -5,
  },
  {
    id: 'gold-a',
    axis: 'y',
    origin: 'center top',
    at: 0.40,
    duration: 0.20,
    scanAxis: 'y',
    scanFrom: -10,
    scanTo: 33,
  },
  {
    id: 'gold-b',
    axis: 'y',
    origin: 'center bottom',
    at: 0.51,
    duration: 0.19,
    scanAxis: 'y',
    scanFrom: 69,
    scanTo: 24,
  },
];
